
[auth]
enable_signup = true

[functions.upload-intake-evidence]
enabled = true
verify_jwt = false
import_map = "./functions/upload-intake-evidence/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-intake-evidence/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-intake-evidence/*.html" ]
