import type { ActivityItem } from "./ActivitiesView";

// Fuente única de la agenda pública. Cada registro conserva su `sourceUrl`
// verificable; la curaduría manual (coordenadas y selección) vive aquí y no
// se regenera automáticamente desde `public/agenda.json`.
export const AGENDA_ACTIVITIES: ActivityItem[] = [
  {
    "id": "uni3-musica-folklorica",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "Música folclórica rioplatense",
    "place": "UNI3 · Sede Eduardo Acevedo (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 09:00",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Música folclórica rioplatense.",
    "organizer": "UNI3 · Sede Eduardo Acevedo",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-gen-gimnasia",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 10:00 a 11:00 / Jueves 13 · 14:30 a 15:30",
    "color": "#087443",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Gimnasia para envejecimiento activo y saludable.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-carrasco-taichi",
    "icon": "☯️",
    "category": "MOVIMIENTO",
    "title": "Tai chi",
    "place": "Espacio Integral para Personas Mayores (Camino Carrasco)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 10:30 a 12:00",
    "color": "#087443",
    "lat": -34.869,
    "lng": -56.116,
    "description": "Práctica de tai chi en el Espacio Integral para Personas Mayores.",
    "organizer": "Espacio Integral para Personas Mayores",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "tacuarembo-jurasica",
    "icon": "🦕",
    "category": "CULTURA",
    "title": "Expo Experiencia Jurásica",
    "place": "Club Democrático (Tacuarembó)",
    "zone": "Tacuarembó",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Disponible hasta el domingo 16 · horarios a confirmar",
    "color": "#e83e6f",
    "lat": -31.72,
    "lng": -55.98,
    "description": "Exposición temática familiar.",
    "organizer": "Club Democrático",
    "sourceUrl": "https://mientrada.com.uy/agenda-geral"
  },
  {
    "id": "rocha-aleteos",
    "icon": "🦋",
    "category": "CULTURA",
    "title": "Muestra «Aleteos y Trazos»",
    "place": "Espacio Arte Sotavento (La Paloma)",
    "zone": "Rocha",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Disponible del 2 al 23 de agosto · horario a confirmar",
    "color": "#e83e6f",
    "lat": -34.657,
    "lng": -54.164,
    "description": "Muestra sobre biodiversidad y lagunas de Rocha.",
    "organizer": "Espacio Arte Sotavento",
    "sourceUrl": "https://turismorocha.gub.uy/eventos/2026/08/02/aleteos-y-trazos-4913"
  },
  {
    "id": "im-teatro-ccz14",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Teatro",
    "place": "Salón Multiuso Personas Mayores CCZ 14 (Paso Molino)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 12:30 a 14:30",
    "color": "#e83e6f",
    "lat": -34.862,
    "lng": -56.207,
    "description": "Taller territorial de teatro para personas mayores.",
    "organizer": "Salón Multiuso Personas Mayores CCZ 14",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-gen-geronto",
    "icon": "🧘",
    "category": "MOVIMIENTO",
    "title": "Gerontopsicomotricidad",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 13:00 a 15:00",
    "color": "#087443",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Propuesta corporal y de estimulación para personas mayores.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "gym-afaf3",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cooperativa AFAF 3 (Malvín Norte)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 13:00 / Miércoles 12 · 15:00",
    "color": "#087443",
    "lat": -34.877,
    "lng": -56.115,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cooperativa AFAF 3",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "ib-ia-rivera",
    "icon": "🤖",
    "category": "APRENDER",
    "title": "Inteligencia Artificial 2",
    "place": "APENJUR (Rivera)",
    "zone": "Rivera",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 13:15",
    "color": "#6941c6",
    "lat": -30.905,
    "lng": -55.55,
    "description": "Taller introductorio sobre qué es la inteligencia artificial y para qué puede utilizarse.",
    "organizer": "APENJUR",
    "sourceUrl": "https://www.bps.gub.uy/19355/programa-ibirapita.html"
  },
  {
    "id": "gym-club-misterio",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Centro Cultural Casa del Vecino Misterio (Unión)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 13:30",
    "color": "#087443",
    "lat": -34.887,
    "lng": -56.136,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Centro Cultural Casa del Vecino Misterio",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "uni3-psicologia-lunes",
    "icon": "🧠",
    "category": "APRENDER",
    "title": "Psicología",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 13:30",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Psicología.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "gym-covine5",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Covine 5 (Punta de Rieles)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y viernes 14 · 13:45",
    "color": "#087443",
    "lat": -34.842,
    "lng": -56.091,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Covine 5",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-mesa1",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cooperativa de Viviendas Mesa 1 (Camino Carrasco)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 13:45",
    "color": "#087443",
    "lat": -34.868,
    "lng": -56.124,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cooperativa de Viviendas Mesa 1",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-alba-roballo",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Centro Cultural Alba Roballo (La Teja)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 · 14:00",
    "color": "#087443",
    "lat": -34.869,
    "lng": -56.234,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Centro Cultural Alba Roballo",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-cabana-anaya",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cabaña Anaya (Manga)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 14:00",
    "color": "#087443",
    "lat": -34.798,
    "lng": -56.132,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cabaña Anaya",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-julia-arevalo",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Centro Cultural Julia Arévalo (Casabó)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 14:00",
    "color": "#087443",
    "lat": -34.886,
    "lng": -56.275,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Centro Cultural Julia Arévalo",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-barradas",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Espacio Barradas · Museo Blanes (Prado)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 14:00",
    "color": "#087443",
    "lat": -34.858,
    "lng": -56.202,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Espacio Barradas · Museo Blanes",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "mvd-huerta-beherens",
    "icon": "🌱",
    "category": "COMUNIDAD",
    "title": "Huerta comunitaria en la Quinta de Beherens",
    "place": "Quinta de Beherens · Escuela de Jardinería (Prado)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente",
      "Cultura"
    ],
    "time": "Lunes 10 y viernes 14 · desde las 14:00",
    "color": "#e83e6f",
    "lat": -34.8627,
    "lng": -56.207,
    "description": "Espacio comunitario para participar del cuidado de una huerta creada por vecinas y vecinos en los canteros de la Quinta de Beherens.",
    "organizer": "Vecinas y vecinos de la zona · Escuela de Jardinería de la IM",
    "sourceUrl": "https://escueladejardineria.montevideo.gub.uy/actividades/huerta-comunitaria-en-la-quinta-de-beherens"
  },
  {
    "id": "im-gen-activamente",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Lunes 10 · 15:00 a 17:00",
    "color": "#d97706",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Actividad grupal de estimulación cognitiva y participación.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-viajes-pres",
    "icon": "🧳",
    "category": "COMUNIDAD",
    "title": "Compartiendo viajes",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Lunes 10 · 15:30",
    "color": "#d97706",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Compartiendo viajes.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "gym-coop-3abril",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cooperativa 3 de Abril (Nuevo París)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 15:30",
    "color": "#087443",
    "lat": -34.849,
    "lng": -56.229,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cooperativa 3 de Abril",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-casal-catala",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Casal Catalá (Palermo)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 15:30",
    "color": "#087443",
    "lat": -34.909,
    "lng": -56.179,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Casal Catalá",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-club-funsa",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Club Funsa (Maroñas)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 15:30",
    "color": "#087443",
    "lat": -34.862,
    "lng": -56.132,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Club Funsa",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "maca-taller-teatro",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Taller de Teatro MACA",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Cultura"
    ],
    "time": "Lunes 10 · 15:45 a 18:00",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Inicio de un taller de teatro que continúa hasta diciembre; no requiere experiencia previa.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "gym-polideportivo-colon",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Espacio Polideportivo Colón (Colón)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Lunes 10 y miércoles 12 · 16:00",
    "color": "#087443",
    "lat": -34.805,
    "lng": -56.218,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Espacio Polideportivo Colón",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "uni3-viajes-zoom",
    "icon": "🧳",
    "category": "COMUNIDAD",
    "title": "Compartiendo viajes",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Lunes 10 · 17:00",
    "color": "#d97706",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Compartiendo viajes.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "can-foto-canticos",
    "icon": "📷",
    "category": "CULTURA",
    "title": "Exposición fotográfica «Entre cánticos y silencios»",
    "place": "Centro Cultural de Parque del Plata (Parque del Plata)",
    "zone": "Canelones",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Lunes 10 · 20:00 · muestra abierta hasta el 28 de agosto",
    "color": "#e83e6f",
    "lat": -34.767,
    "lng": -55.709,
    "description": "Apertura de una exposición fotográfica.",
    "organizer": "Centro Cultural de Parque del Plata",
    "sourceUrl": "https://www.imcanelones.gub.uy/agenda-cultural/exposicion-fotografica-entre-canticos-silencios-imagenes-del-silencio-fotografos"
  },
  {
    "id": "can-huerta-agroecologica-patio",
    "icon": "🌾",
    "category": "APRENDER",
    "title": "Huerta agroecológica",
    "place": "Patio Cultural (Ciudad de la Costa)",
    "zone": "Canelones",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender"
    ],
    "time": "Martes 11 y viernes 14 · horario por confirmar",
    "color": "#6941c6",
    "lat": -34.826,
    "lng": -55.956,
    "description": "Taller municipal de huerta agroecológica publicado para los martes y viernes en el Patio Cultural de Ciudad de la Costa.",
    "organizer": "Gobierno de Canelones",
    "sourceUrl": "https://www.imcanelones.gub.uy/sites/default/files/2026-02/CULTURA-%20Talleres%202026%20compressed.pdf"
  },
  {
    "id": "gym-club-artigas",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Club Artigas (Lezica)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y viernes 14 · 08:30",
    "color": "#087443",
    "lat": -34.801,
    "lng": -56.236,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Club Artigas",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "im-geronto-crece",
    "icon": "🧘",
    "category": "MOVIMIENTO",
    "title": "Gerontopsicomotricidad",
    "place": "Crece Flor de Maroñas (Flor de Maroñas)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 · 09:30 a 11:30",
    "color": "#087443",
    "lat": -34.851,
    "lng": -56.12,
    "description": "Taller territorial de gerontopsicomotricidad.",
    "organizer": "Crece Flor de Maroñas",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-reflexiones-literarias",
    "icon": "📚",
    "category": "CULTURA",
    "title": "Reflexiones literarias: el tiempo y lo no dicho",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Martes 11 · 10:30",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Reflexiones literarias: el tiempo y lo no dicho.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "gym-villa-centauro",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Espacio Cultural y Recreativo Villa Centauro (Villa García)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 12:45",
    "color": "#087443",
    "lat": -34.806,
    "lng": -56.059,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Espacio Cultural y Recreativo Villa Centauro",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-complejo-bps",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Complejo BPS (Prado)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 13:30",
    "color": "#087443",
    "lat": -34.864,
    "lng": -56.198,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Complejo BPS",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-yatay",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Comisión Vecinal Yatay (Paso de las Duranas)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 13:30",
    "color": "#087443",
    "lat": -34.856,
    "lng": -56.196,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Comisión Vecinal Yatay",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-coviunpro",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cooperativa Coviunpro (Casavalle)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 13:30",
    "color": "#087443",
    "lat": -34.823,
    "lng": -56.158,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cooperativa Coviunpro",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-cedel-casavalle",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Cedel Casavalle (Casavalle)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 13:45",
    "color": "#087443",
    "lat": -34.821,
    "lng": -56.154,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Cedel Casavalle",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "uni3-antropologia",
    "icon": "🧭",
    "category": "APRENDER",
    "title": "Antropología",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Martes 11 · 14:00",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Antropología.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-taichi-lgbti",
    "icon": "☯️",
    "category": "MOVIMIENTO",
    "title": "Tai chi",
    "place": "Centro LGBTIQ+ de Montevideo (Palermo)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 · 14:00 a 15:30",
    "color": "#087443",
    "lat": -34.906,
    "lng": -56.187,
    "description": "Taller de tai chi para personas mayores.",
    "organizer": "Centro LGBTIQ+ de Montevideo",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-gen-literario",
    "icon": "📚",
    "category": "CULTURA",
    "title": "Taller literario",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Cultura",
      "Conocer gente"
    ],
    "time": "Martes 11 · 14:00 a 16:00",
    "color": "#e83e6f",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Lectura y escritura en un espacio grupal.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "gym-salesiano",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Centro Juvenil Salesiano (Sayago)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 15:00",
    "color": "#087443",
    "lat": -34.846,
    "lng": -56.195,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Centro Juvenil Salesiano",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "uni3-tango-whatsapp",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "Historia del tango",
    "place": "WhatsApp (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Martes 11 · 15:00",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Historia del tango.",
    "organizer": "WhatsApp",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "gym-club-colonia",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Club Colonia (Prado)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 15:30",
    "color": "#087443",
    "lat": -34.861,
    "lng": -56.194,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Club Colonia",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-velodromo",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Velódromo Municipal (Parque Batlle)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 15:30",
    "color": "#087443",
    "lat": -34.893,
    "lng": -56.153,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Velódromo Municipal",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-espacio-modelo",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Espacio Modelo (Mercado Modelo)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 15:30",
    "color": "#087443",
    "lat": -34.872,
    "lng": -56.156,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Espacio Modelo",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "gym-club-municipal",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Club Municipal (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Martes 11 y jueves 13 · 15:45",
    "color": "#087443",
    "lat": -34.906,
    "lng": -56.192,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Club Municipal",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "mvd-rio-adentro",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Documental «Río adentro»",
    "place": "Sala Zitarrosa (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Martes 11 · 19:30",
    "color": "#e83e6f",
    "lat": -34.906,
    "lng": -56.188,
    "description": "Exhibición documental en Sala Zitarrosa.",
    "organizer": "Sala Zitarrosa",
    "sourceUrl": "https://municipiob.montevideo.gub.uy/actividades-en-el-b"
  },
  {
    "id": "gym-plaza1",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Plaza de Deportes N.º 1 (Ciudad Vieja)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 09:30 / Viernes 14 · 10:30",
    "color": "#087443",
    "lat": -34.908,
    "lng": -56.21,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Plaza de Deportes N.º 1",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "im-act-blanes",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Museo Blanes · Espacio Barradas (Prado)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 10:00 a 12:00",
    "color": "#d97706",
    "lat": -34.859,
    "lng": -56.205,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Museo Blanes · Espacio Barradas",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "flores-manipulacion",
    "icon": "🥗",
    "category": "APRENDER",
    "title": "Curso de manipulación de alimentos",
    "place": "Sala Larrañaga (Trinidad)",
    "zone": "Flores",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender"
    ],
    "time": "Miércoles 12 · 10:00",
    "color": "#6941c6",
    "lat": -33.516,
    "lng": -56.899,
    "description": "Curso de capacitación sobre manipulación de alimentos.",
    "organizer": "Sala Larrañaga",
    "sourceUrl": "https://agenda.flores.gub.uy/"
  },
  {
    "id": "im-gen-danza",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Danza y expresión corporal",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 10:00 a 12:00 / Viernes 14 · 14:00 a 16:00",
    "color": "#087443",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Danza y expresión corporal para personas mayores.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-danzas-folcloricas",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Danzas folclóricas",
    "place": "UNI3 · Ana Monterroso de Lavalleja (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 10:00",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Danzas folclóricas.",
    "organizer": "UNI3 · Ana Monterroso de Lavalleja",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "flores-jornada-musical",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "Jornada educativa y musical en Biblioteca",
    "place": "Casa de la Cultura (Trinidad)",
    "zone": "Flores",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Miércoles 12 · 10:00",
    "color": "#e83e6f",
    "lat": -33.516,
    "lng": -56.899,
    "description": "Jornada educativa y musical.",
    "organizer": "Casa de la Cultura",
    "sourceUrl": "https://agenda.flores.gub.uy/"
  },
  {
    "id": "im-teatro-saludmental",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Teatro",
    "place": "Casa Comunitaria de Promoción de Salud Mental (Colón)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 10:00 a 12:00",
    "color": "#e83e6f",
    "lat": -34.829,
    "lng": -56.216,
    "description": "Taller territorial de teatro para personas mayores.",
    "organizer": "Casa Comunitaria de Promoción de Salud Mental",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-frances",
    "icon": "🇫🇷",
    "category": "APRENDER",
    "title": "Francés intermedio",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 10:15",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Francés intermedio.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-act-guyunusa",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Centro Cultural Guyunusa (Brazo Oriental)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 13:00 a 15:00",
    "color": "#d97706",
    "lat": -34.845,
    "lng": -56.161,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Centro Cultural Guyunusa",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-psicologia-miercoles",
    "icon": "🧠",
    "category": "APRENDER",
    "title": "Psicología",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 13:45",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Psicología.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "gym-parque-amistad",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Parque de la Amistad (Parque Batlle)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 14:00 / Viernes 14 · 13:30",
    "color": "#087443",
    "lat": -34.895,
    "lng": -56.147,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Parque de la Amistad",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "uni3-literatura-artes",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Literatura y artes escénicas: una mirada filosófica",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 14:00",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Literatura y artes escénicas: una mirada filosófica.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-gen-teatro",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Teatro",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 14:00 a 16:00",
    "color": "#e83e6f",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Taller de teatro para personas mayores.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-geronto-ccz14",
    "icon": "🧘",
    "category": "MOVIMIENTO",
    "title": "Gerontopsicomotricidad",
    "place": "Salón Multiuso Personas Mayores CCZ 14 (Paso Molino)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 14:30 a 16:30",
    "color": "#087443",
    "lat": -34.862,
    "lng": -56.207,
    "description": "Taller territorial de gerontopsicomotricidad.",
    "organizer": "Salón Multiuso Personas Mayores CCZ 14",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "ib-correo-tacuarembo",
    "icon": "✉️",
    "category": "APRENDER",
    "title": "Correo electrónico",
    "place": "UNI3 Tacuarembó (Tacuarembó)",
    "zone": "Tacuarembó",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 16:00 a 18:00",
    "color": "#6941c6",
    "lat": -31.72,
    "lng": -55.98,
    "description": "Uso de Gmail para comunicarse y acceder a servicios digitales.",
    "organizer": "UNI3 Tacuarembó",
    "sourceUrl": "https://www.bps.gub.uy/19355/programa-ibirapita.html"
  },
  {
    "id": "uni3-mosaiquismo",
    "icon": "🎨",
    "category": "CULTURA",
    "title": "Mosaiquismo",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Miércoles 12 · 16:15",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Mosaiquismo.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "rocha-historias-pago",
    "icon": "📚",
    "category": "CULTURA",
    "title": "Presentación del libro «Historias del Pago Grande»",
    "place": "Salón Saltarines (Chuy)",
    "zone": "Rocha",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Miércoles 12 · 20:00",
    "color": "#e83e6f",
    "lat": -33.697,
    "lng": -53.456,
    "description": "Presentación de la publicación de Félix Flugel sobre historias del Pago Grande.",
    "organizer": "Salón Saltarines",
    "sourceUrl": "https://turismorocha.gub.uy/eventos/2026/08/12/historias-del-pago-grande-4903"
  },
  {
    "id": "uni3-radio",
    "icon": "📻",
    "category": "APRENDER",
    "title": "Taller de radio",
    "place": "UNI3 · Sede Arenal Grande (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Jueves 13 · 09:00",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Taller de radio.",
    "organizer": "UNI3 · Sede Arenal Grande",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "flores-kamishibai",
    "icon": "📚",
    "category": "CULTURA",
    "title": "Kamishibai «Una Huerta Disparatada»",
    "place": "Biblioteca Municipal (Trinidad)",
    "zone": "Flores",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Jueves 13 · 09:30",
    "color": "#e83e6f",
    "lat": -33.516,
    "lng": -56.899,
    "description": "Propuesta de narración vinculada a una huerta; puede ser intergeneracional.",
    "organizer": "Biblioteca Municipal",
    "sourceUrl": "https://agenda.flores.gub.uy/"
  },
  {
    "id": "im-act-castillo",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Castillo Parque Rodó (Parque Rodó)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Jueves 13 · 10:00 a 12:00",
    "color": "#d97706",
    "lat": -34.911,
    "lng": -56.168,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Castillo Parque Rodó",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-fisica-cine",
    "icon": "🎬",
    "category": "APRENDER",
    "title": "Historia de la física en la cinematografía",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Cultura",
      "Conocer gente"
    ],
    "time": "Jueves 13 · 10:30",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Historia de la física en la cinematografía.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "uni3-lengua-espanola",
    "icon": "📝",
    "category": "CULTURA",
    "title": "Historia de la lengua española",
    "place": "UNI3 · Sede Eduardo Acevedo (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Jueves 13 · 13:45",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Historia de la lengua española.",
    "organizer": "UNI3 · Sede Eduardo Acevedo",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-act-ccz10",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Comuna Mujer CCZ 10 (Piedras Blancas)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Jueves 13 · 14:00 a 16:00",
    "color": "#d97706",
    "lat": -34.816,
    "lng": -56.137,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Comuna Mujer CCZ 10",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-act-mesa1",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Mesa 1 (Camino Carrasco)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Jueves 13 · 14:00 a 16:00",
    "color": "#d97706",
    "lat": -34.868,
    "lng": -56.124,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Mesa 1",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "sj-master-guitarra",
    "icon": "🎸",
    "category": "APRENDER",
    "title": "Master class de guitarra con Gonzalo Victoria",
    "place": "Sala Eduardo Carbajal (San José de Mayo)",
    "zone": "San José",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Cultura"
    ],
    "time": "Jueves 13 · 14:00",
    "color": "#e83e6f",
    "lat": -34.337,
    "lng": -56.714,
    "description": "Clase magistral de guitarra.",
    "organizer": "Sala Eduardo Carbajal",
    "sourceUrl": "https://www.radio41.com.uy/index.php/columnistas-de-segun-como-se-mire/item/16819-cartelera-de-agosto-en-san-jose-mira-la-lista-completa-de-espectaculos-y-exposiciones-en-el-maccio-y-el-espacio-cultural"
  },
  {
    "id": "maca-cine-montana",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Cine: «Un día para soñar» + «Los hijos de la montaña»",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Jueves 13 · 15:30 a 16:40",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Doble función de cine en el MACA.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "gym-parque-bellan",
    "icon": "🏃",
    "category": "MOVIMIENTO",
    "title": "Gimnasia para personas mayores",
    "place": "Parque Bellán (Aguada)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Jueves 13 · 15:30",
    "color": "#087443",
    "lat": -34.887,
    "lng": -56.188,
    "description": "Clase gratuita de gimnasia para personas mayores, abierta a la comunidad.",
    "organizer": "Parque Bellán",
    "sourceUrl": "https://montevideo.gub.uy/areas-tematicas/deportes/actividades-fisicas-para-personas-mayores"
  },
  {
    "id": "im-gen-taichi",
    "icon": "☯️",
    "category": "MOVIMIENTO",
    "title": "Tai chi",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Jueves 13 · 15:30 a 17:00 / Viernes 14 · 12:00 a 13:30",
    "color": "#087443",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Práctica de tai chi para personas mayores.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "sj-recital-guitarra",
    "icon": "🎸",
    "category": "CULTURA",
    "title": "Recital de guitarra",
    "place": "Sala Eduardo Carbajal (San José de Mayo)",
    "zone": "San José",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Jueves 13 · 19:00",
    "color": "#e83e6f",
    "lat": -34.337,
    "lng": -56.714,
    "description": "Recital de guitarra.",
    "organizer": "Sala Eduardo Carbajal",
    "sourceUrl": "https://www.radio41.com.uy/index.php/columnistas-de-segun-como-se-mire/item/16819-cartelera-de-agosto-en-san-jose-mira-la-lista-completa-de-espectaculos-y-exposiciones-en-el-maccio-y-el-espacio-cultural"
  },
  {
    "id": "uni3-filosofia",
    "icon": "💭",
    "category": "APRENDER",
    "title": "Filosofía para la vida",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 09:30",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Filosofía para la vida.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "uni3-aleman",
    "icon": "🇩🇪",
    "category": "APRENDER",
    "title": "Lengua y cultura alemana",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 10:00",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Lengua y cultura alemana.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-gen-relajacion",
    "icon": "🌿",
    "category": "MOVIMIENTO",
    "title": "Relajación",
    "place": "Espacio Generacciones (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Moverme",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 10:00 a 12:00",
    "color": "#087443",
    "lat": -34.8995,
    "lng": -56.1785,
    "description": "Taller de relajación para personas mayores.",
    "organizer": "Espacio Generacciones",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-economia",
    "icon": "📈",
    "category": "APRENDER",
    "title": "Economía",
    "place": "UNI3 · Sede Eduardo Acevedo (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 10:30",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Economía.",
    "organizer": "UNI3 · Sede Eduardo Acevedo",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "im-carrasco-activamente",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Espacio Integral para Personas Mayores (Camino Carrasco)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Viernes 14 · 11:15 a 13:15",
    "color": "#d97706",
    "lat": -34.869,
    "lng": -56.116,
    "description": "Estimulación cognitiva y participación grupal.",
    "organizer": "Espacio Integral para Personas Mayores",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-act-tresombues",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Centro Cívico Tres Ombúes (Tres Ombúes)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Viernes 14 · 13:30 a 15:30",
    "color": "#d97706",
    "lat": -34.845,
    "lng": -56.245,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Centro Cívico Tres Ombúes",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-act-amistad",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "Parque de la Amistad (Parque Batlle)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Viernes 14 · 14:45 a 16:45",
    "color": "#d97706",
    "lat": -34.895,
    "lng": -56.147,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "Parque de la Amistad",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "im-act-ccz17",
    "icon": "🧩",
    "category": "COMUNIDAD",
    "title": "ActivaMENTE",
    "place": "CCZ 17 (Cerro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente"
    ],
    "time": "Viernes 14 · 15:00 a 17:00",
    "color": "#d97706",
    "lat": -34.867,
    "lng": -56.251,
    "description": "Taller territorial de estimulación cognitiva y participación para personas mayores.",
    "organizer": "CCZ 17",
    "sourceUrl": "https://montevideo.gub.uy/noticias/talleres-para-personas-mayores-0"
  },
  {
    "id": "uni3-historia-arte",
    "icon": "🖼️",
    "category": "CULTURA",
    "title": "Historia del arte",
    "place": "Zoom (Virtual)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 15:30",
    "color": "#e83e6f",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Historia del arte.",
    "organizer": "Zoom",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "uni3-portugues",
    "icon": "🇧🇷",
    "category": "APRENDER",
    "title": "Portugués",
    "place": "UNI3 · Sede Eduardo Acevedo (Centro)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender",
      "Conocer gente"
    ],
    "time": "Viernes 14 · 16:00",
    "color": "#6941c6",
    "lat": -34.899,
    "lng": -56.178,
    "description": "Taller de UNI3: Portugués.",
    "organizer": "UNI3 · Sede Eduardo Acevedo",
    "sourceUrl": "https://uni3.uy/"
  },
  {
    "id": "mnav-belmonte",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Cine: «Belmonte»",
    "place": "Museo Nacional de Artes Visuales (Parque Rodó)",
    "zone": "Montevideo",
    "moment": "Entre semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 18:00",
    "color": "#e83e6f",
    "lat": -34.913,
    "lng": -56.165,
    "description": "Proyección dentro del ciclo de cine y artes visuales del MNAV.",
    "organizer": "Museo Nacional de Artes Visuales",
    "sourceUrl": "https://mnav.gub.uy/cms.php?id=ciclodecine2026"
  },
  {
    "id": "can-cine-chacra",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Película «Chacra»",
    "place": "Sociedad de Fomento Rural Los Arenales (San Jacinto)",
    "zone": "Canelones",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 18:00",
    "color": "#e83e6f",
    "lat": -34.545,
    "lng": -55.871,
    "description": "Proyección cinematográfica en una sociedad de fomento rural.",
    "organizer": "Sociedad de Fomento Rural Los Arenales",
    "sourceUrl": "https://www.imcanelones.gub.uy/agenda-cultural/cine-pelicula-chacra"
  },
  {
    "id": "flores-piquin",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Hernán Piquín: «Me verás volver»",
    "place": "Teatro Artigas (Trinidad)",
    "zone": "Flores",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 20:00",
    "color": "#e83e6f",
    "lat": -33.516,
    "lng": -56.899,
    "description": "Espectáculo de danza y música.",
    "organizer": "Teatro Artigas",
    "sourceUrl": "https://agenda.flores.gub.uy/"
  },
  {
    "id": "rocha-ziba",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Muestra de Zibá Dance Company",
    "place": "Teatro 25 de Mayo (Rocha)",
    "zone": "Rocha",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 20:00",
    "color": "#e83e6f",
    "lat": -34.483,
    "lng": -54.333,
    "description": "Muestra de danza en el Teatro 25 de Mayo.",
    "organizer": "Teatro 25 de Mayo",
    "sourceUrl": "https://turismorocha.gub.uy/eventos/2026/08/14/muestra-de-danza-ziba-4924"
  },
  {
    "id": "rocha-petru",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "Petru Valensky en café concert",
    "place": "Centro Cultural de Chuy (Chuy)",
    "zone": "Rocha",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 20:00",
    "color": "#e83e6f",
    "lat": -33.697,
    "lng": -53.456,
    "description": "Espectáculo de café concert.",
    "organizer": "Centro Cultural de Chuy",
    "sourceUrl": "https://turismorocha.gub.uy/eventos/2026/08/14/petru-valenski-en-cafe-concert-4891"
  },
  {
    "id": "sj-diez-anos",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "«10 años haciéndote reír»",
    "place": "Teatro Macció (San José de Mayo)",
    "zone": "San José",
    "moment": "Entre semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Viernes 14 · 20:30",
    "color": "#e83e6f",
    "lat": -34.337,
    "lng": -56.714,
    "description": "Espectáculo de humor.",
    "organizer": "Teatro Macció",
    "sourceUrl": "https://www.radio41.com.uy/index.php/columnistas-de-segun-como-se-mire/item/16819-cartelera-de-agosto-en-san-jose-mira-la-lista-completa-de-espectaculos-y-exposiciones-en-el-maccio-y-el-espacio-cultural"
  },
  {
    "id": "sodre-camara-oscura",
    "icon": "📷",
    "category": "APRENDER",
    "title": "Cámara oscura",
    "place": "Archivo Nacional de la Imagen y la Palabra (Ciudad Vieja)",
    "zone": "Montevideo",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Aprender"
    ],
    "time": "Sábado 15 · disponible de 10:00 a 14:00",
    "color": "#6941c6",
    "lat": -34.906,
    "lng": -56.204,
    "description": "Experiencia para comprender de forma vivencial el fenómeno físico de la cámara oscura.",
    "organizer": "Archivo Nacional de la Imagen y la Palabra",
    "sourceUrl": "https://sodre.gub.uy/actividad/taller-imagenes-al-sol-fotografia-memoria-y-experimentacion/"
  },
  {
    "id": "mvd-huerta-malvin-norte",
    "icon": "🪴",
    "category": "COMUNIDAD",
    "title": "Huerta comunitaria",
    "place": "Centro Cultural Malvín Norte (Malvín Norte)",
    "zone": "Montevideo",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Conocer gente",
      "Cultura"
    ],
    "time": "Sábado 15 · 10:00 a 12:00",
    "color": "#e83e6f",
    "lat": -34.8792,
    "lng": -56.1188,
    "description": "Encuentro gratuito de huerta comunitaria en el Centro Cultural Malvín Norte.",
    "organizer": "Centro Cultural Malvín Norte · Municipio E",
    "sourceUrl": "https://municipioe.montevideo.gub.uy/cursos-talleres-y-actividades-deportivas-2025"
  },
  {
    "id": "sodre-imagenes-sol",
    "icon": "📷",
    "category": "CULTURA",
    "title": "Imágenes al sol: fotografía, memoria y experimentación",
    "place": "Archivo Nacional de la Imagen y la Palabra (Ciudad Vieja)",
    "zone": "Montevideo",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 11:00 a 13:00",
    "color": "#e83e6f",
    "lat": -34.906,
    "lng": -56.204,
    "description": "Taller práctico de cianotipia, memoria e imágenes; no requiere conocimientos previos.",
    "organizer": "Archivo Nacional de la Imagen y la Palabra",
    "sourceUrl": "https://sodre.gub.uy/actividad/taller-imagenes-al-sol-fotografia-memoria-y-experimentacion/"
  },
  {
    "id": "salto-antiguo",
    "icon": "📷",
    "category": "CULTURA",
    "title": "Exposición de Salto Antiguo",
    "place": "Mercado 18 de Julio (Salto)",
    "zone": "Salto",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · horario a confirmar",
    "color": "#e83e6f",
    "lat": -31.388,
    "lng": -57.96,
    "description": "Exposición de fotografías, recuerdos e historias de la ciudad.",
    "organizer": "Mercado 18 de Julio",
    "sourceUrl": "https://www.salto.gub.uy/eventos"
  },
  {
    "id": "maca-nenette-doc",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Documental «Je suis Nenette»",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 14:00 a 14:50",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Proyección documental; la reserva es independiente de la del concierto.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "lavalleja-feria-varela",
    "icon": "🛍️",
    "category": "COMUNIDAD",
    "title": "Expo Feria de Artesanos y Emprendedores",
    "place": "Plaza de José Pedro Varela (José Pedro Varela)",
    "zone": "Lavalleja",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 14:00",
    "color": "#e83e6f",
    "lat": -33.455,
    "lng": -54.536,
    "description": "Feria de artesanos y emprendimientos locales.",
    "organizer": "Plaza de José Pedro Varela",
    "sourceUrl": "https://www.holavarela.uy/eventos"
  },
  {
    "id": "maca-nenette-concierto",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "Melaní Luraschi presenta «Je suis Nenette»",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 16:30 a 18:00",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Concierto con repertorio inspirado en la vida y obra de Nenette Pepin.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "rocha-federico",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "«Hola, soy Federico»",
    "place": "Centro Cultural Nacional La Paloma (La Paloma)",
    "zone": "Rocha",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 19:00",
    "color": "#e83e6f",
    "lat": -34.657,
    "lng": -54.164,
    "description": "Poemas, teatro, canciones y flamenco en torno a Federico García Lorca.",
    "organizer": "Centro Cultural Nacional La Paloma",
    "sourceUrl": "https://turismorocha.gub.uy/eventos/2026/08/15/hola-soy-federico-4895"
  },
  {
    "id": "lavalleja-mezcolanza",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "«Mezcolanza» · Coral Maysupí y Ensamble Da Capo",
    "place": "Parroquia San Carlos Borromeo (José Pedro Varela)",
    "zone": "Lavalleja",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 19:00",
    "color": "#e83e6f",
    "lat": -33.455,
    "lng": -54.536,
    "description": "Concierto coral con música de los siglos XVI y XVII.",
    "organizer": "Parroquia San Carlos Borromeo",
    "sourceUrl": "https://www.holavarela.uy/eventos"
  },
  {
    "id": "sj-copla-alta",
    "icon": "🎵",
    "category": "CULTURA",
    "title": "Copla Alta: «Pulso»",
    "place": "Teatro Macció (San José de Mayo)",
    "zone": "San José",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Sábado 15 · 20:30",
    "color": "#e83e6f",
    "lat": -34.337,
    "lng": -56.714,
    "description": "Espectáculo musical.",
    "organizer": "Teatro Macció",
    "sourceUrl": "https://www.radio41.com.uy/index.php/columnistas-de-segun-como-se-mire/item/16819-cartelera-de-agosto-en-san-jose-mira-la-lista-completa-de-espectaculos-y-exposiciones-en-el-maccio-y-el-espacio-cultural"
  },
  {
    "id": "maca-tango",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Clase de tango y milonga",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Domingo 16 · 14:00 a 18:00",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Clase y milonga entre obras, arquitectura y paisaje; propuesta para explorar el abrazo y la caminata compartida.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "maca-uruguay-salvaje",
    "icon": "🎬",
    "category": "CULTURA",
    "title": "Cine: «Uruguay Salvaje»",
    "place": "Museo de Arte Contemporáneo Atchugarry (Manantiales)",
    "zone": "Maldonado",
    "moment": "Fin de semana",
    "freeOnly": true,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Domingo 16 · 16:00 a 17:00",
    "color": "#e83e6f",
    "lat": -34.89,
    "lng": -54.83,
    "description": "Documental sobre la biodiversidad del territorio uruguayo.",
    "organizer": "Museo de Arte Contemporáneo Atchugarry",
    "sourceUrl": "https://macamuseo.org/eventosmaca"
  },
  {
    "id": "salto-bajo-mar",
    "icon": "🎭",
    "category": "CULTURA",
    "title": "«Bajo el mar»",
    "place": "Teatro Larrañaga (Salto)",
    "zone": "Salto",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Domingo 16 · 18:00",
    "color": "#e83e6f",
    "lat": -31.388,
    "lng": -57.96,
    "description": "Espectáculo de teatro y danza.",
    "organizer": "Teatro Larrañaga",
    "sourceUrl": "https://www.salto.gub.uy/eventos"
  },
  {
    "id": "sj-gala-ballet",
    "icon": "💃",
    "category": "CULTURA",
    "title": "Gala de la Uruguay International Ballet Competition",
    "place": "Teatro Macció (San José de Mayo)",
    "zone": "San José",
    "moment": "Fin de semana",
    "freeOnly": false,
    "accessible": false,
    "smallGroups": true,
    "interests": [
      "Cultura"
    ],
    "time": "Domingo 16 · 20:00",
    "color": "#e83e6f",
    "lat": -34.337,
    "lng": -56.714,
    "description": "Gala de ballet.",
    "organizer": "Teatro Macció",
    "sourceUrl": "https://www.radio41.com.uy/index.php/columnistas-de-segun-como-se-mire/item/16819-cartelera-de-agosto-en-san-jose-mira-la-lista-completa-de-espectaculos-y-exposiciones-en-el-maccio-y-el-espacio-cultural"
  }
];
