-- Arandu: cut over the operational ELEPEM registry to two direct tables.
--
-- This first phase is reversible and deliberately keeps every legacy table.
-- The destructive cleanup is a separate, manually gated maintenance step.

begin;

set local lock_timeout = '10s';
set local statement_timeout = '120s';

select pg_advisory_xact_lock(hashtextextended('arandu:elepem-flat-cutover', 0));

lock table
  elepem_core.facilities,
  elepem_core.facility_names,
  elepem_core.facility_addresses,
  elepem_core.facility_contacts,
  elepem_core.facility_social_accounts,
  elepem_core.facility_operators,
  elepem_core.organizations,
  elepem_core.facility_administrative_events,
  elepem_core.facility_geocodes,
  elepem_core.facility_observation_links,
  elepem_core.facility_public_profiles,
  elepem_core.legacy_facility_map,
  discovery_private.facility_source_observations,
  discovery_private.facility_candidates,
  discovery_private.facility_external_ids,
  public.intake_reports,
  elepem_core.facility_experience_publications,
  public.facility_document_status_reviews,
  public.facility_change_publications
in share row exclusive mode;

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create or replace function app_private.elepem_external_urls_valid(values_to_check text[])
returns boolean
language sql
immutable
strict
set search_path = pg_catalog
as $$
  select coalesce(bool_and(
    item = ''
    or (
      char_length(item) <= 1000
      and item ~* '^https?://'
      and item !~* '^https?://[^/]*supabase\.co(?:/|$)'
      and item !~* '^https?://(?:[^/]*\.)?google\.[^/]+/maps(?:/|$)'
      and item !~* '^https?://maps\.app\.goo\.gl(?:/|$)'
    )
  ), true)
  from unnest(values_to_check) as item;
$$;

revoke all on function app_private.elepem_external_urls_valid(text[])
  from public, anon, authenticated, service_role;

create or replace function app_private.touch_flat_elepem_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function app_private.touch_flat_elepem_updated_at()
  from public, anon, authenticated, service_role;

create table public.elepem (
  id bigint generated by default as identity primary key,
  codigo text not null unique check (char_length(btrim(codigo)) between 1 and 240),
  legacy_id text unique check (legacy_id is null or char_length(btrim(legacy_id)) between 1 and 240),
  nombre text not null check (char_length(btrim(nombre)) between 1 and 300),
  nombres_alternativos text[] not null default '{}',

  departamento text not null check (char_length(btrim(departamento)) between 1 and 100),
  localidad text not null check (char_length(btrim(localidad)) between 1 and 160),
  direccion text not null check (char_length(btrim(direccion)) between 1 and 500),
  lat double precision not null check (lat between -35.2 and -30),
  lng double precision not null check (lng between -58.6 and -53),
  precision_ubicacion text not null check (precision_ubicacion in ('puerta', 'calle', 'referencial')),
  precision_etiqueta text not null check (char_length(btrim(precision_etiqueta)) between 1 and 160),

  telefonos text[] not null default '{}',
  emails text[] not null default '{}',
  sitios_web text[] not null default '{}',
  instagram_urls text[] not null default '{}',
  facebook_urls text[] not null default '{}',
  otras_redes_urls text[] not null default '{}',

  operadores_nombres text[] not null default '{}',
  operadores_tipos text[] not null default '{}',

  precio_mensual_uyu integer check (precio_mensual_uyu is null or precio_mensual_uyu between 10000 and 10000000),
  precio_fecha date,
  precio_incluye text[] not null default '{}',
  precio_fuente_url text,
  precio_es_demo boolean not null default false,

  msp_habilitado boolean not null default false,
  msp_fuente_url text,
  msp_fecha date,
  mides_certificado boolean not null default false,
  mides_fuente_url text,
  mides_fecha date,
  situacion text generated always as (
    case
      when msp_habilitado then 'habilitacion_msp'
      when mides_certificado then 'certificado_social_mides'
      else 'situacion_no_confirmada'
    end
  ) stored,

  descripcion text check (descripcion is null or char_length(btrim(descripcion)) between 1 and 2000),
  imagen_url text check (imagen_url is null or char_length(imagen_url) <= 1000),
  imagen_alt text check (imagen_alt is null or char_length(btrim(imagen_alt)) between 1 and 300),

  google_place_id text check (google_place_id is null or char_length(google_place_id) between 1 and 300),
  google_maps_url text check (
    google_maps_url is null
    or (
      char_length(google_maps_url) <= 1000
      and google_maps_url ~* '^https://((www\.)?google\.[a-z.]+/maps|maps\.google\.[a-z.]+/)'
    )
  ),
  google_verificado_at timestamptz,
  google_verificado_por text check (google_verificado_por is null or char_length(btrim(google_verificado_por)) between 1 and 200),
  osm_ids text[] not null default '{}',
  osm_urls text[] not null default '{}',
  otros_ids_proveedores text[] not null default '{}',
  otros_ids text[] not null default '{}',
  otros_ids_urls text[] not null default '{}',

  fuentes_referencias text[] not null,
  fuentes_urls text[] not null,
  fuentes_tipos text[] not null,
  fuentes_proveedores text[] not null,
  fuentes_fechas date[] not null,
  fuentes_consultadas_at timestamptz[] not null,
  fuentes_campos_respaldados text[] not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint elepem_operator_arrays_aligned check (
    cardinality(operadores_nombres) = cardinality(operadores_tipos)
  ),
  constraint elepem_osm_arrays_aligned check (
    cardinality(osm_ids) = cardinality(osm_urls)
  ),
  constraint elepem_other_id_arrays_aligned check (
    cardinality(otros_ids_proveedores) = cardinality(otros_ids)
    and cardinality(otros_ids) = cardinality(otros_ids_urls)
  ),
  constraint elepem_source_arrays_aligned check (
    cardinality(fuentes_referencias) >= 1
    and cardinality(fuentes_referencias) <= 200
    and cardinality(fuentes_referencias) = cardinality(fuentes_urls)
    and cardinality(fuentes_urls) = cardinality(fuentes_tipos)
    and cardinality(fuentes_tipos) = cardinality(fuentes_proveedores)
    and cardinality(fuentes_proveedores) = cardinality(fuentes_fechas)
    and cardinality(fuentes_fechas) = cardinality(fuentes_consultadas_at)
    and cardinality(fuentes_consultadas_at) = cardinality(fuentes_campos_respaldados)
  ),
  constraint elepem_external_urls_check check (
    app_private.elepem_external_urls_valid(sitios_web)
    and app_private.elepem_external_urls_valid(instagram_urls)
    and app_private.elepem_external_urls_valid(facebook_urls)
    and app_private.elepem_external_urls_valid(otras_redes_urls)
    and app_private.elepem_external_urls_valid(osm_urls)
    and app_private.elepem_external_urls_valid(otros_ids_urls)
    and app_private.elepem_external_urls_valid(fuentes_urls)
  ),
  constraint elepem_price_traceability_check check (
    (precio_mensual_uyu is null and precio_fecha is null and precio_fuente_url is null and not precio_es_demo)
    or (
      precio_mensual_uyu is not null
      and precio_fecha is not null
      and (
        precio_es_demo
        or (
          precio_fuente_url ~* '^https?://'
          and precio_fuente_url !~* '^https?://[^/]*supabase\.co(?:/|$)'
        )
      )
    )
  ),
  constraint elepem_msp_traceability_check check (
    (msp_habilitado and msp_fuente_url ~* '^https?://' and msp_fecha is not null)
    or (not msp_habilitado and msp_fuente_url is null and msp_fecha is null)
  ),
  constraint elepem_mides_traceability_check check (
    (mides_certificado and mides_fuente_url ~* '^https?://' and mides_fecha is not null)
    or (not mides_certificado and mides_fuente_url is null and mides_fecha is null)
  ),
  constraint elepem_google_manual_link_check check (
    (google_place_id is null and google_maps_url is null and google_verificado_at is null and google_verificado_por is null)
    or (
      google_place_id is not null
      and google_maps_url is not null
      and google_verificado_at is not null
      and google_verificado_por is not null
    )
  ),
  constraint elepem_image_pair_check check (
    imagen_url is not null or imagen_alt is null
  )
);

create table public.elepem_sin_ubicacion (
  id bigint generated by default as identity primary key,
  codigo text not null unique check (char_length(btrim(codigo)) between 1 and 240),
  legacy_id text unique check (legacy_id is null or char_length(btrim(legacy_id)) between 1 and 240),
  nombre text not null check (char_length(btrim(nombre)) between 1 and 300),
  nombres_alternativos text[] not null default '{}',
  departamento text not null check (char_length(btrim(departamento)) between 1 and 100),
  localidad text not null check (char_length(btrim(localidad)) between 1 and 160),
  direccion text check (direccion is null or char_length(btrim(direccion)) between 1 and 500),
  telefonos text[] not null default '{}',
  emails text[] not null default '{}',
  sitios_web text[] not null default '{}',
  instagram_urls text[] not null default '{}',
  facebook_urls text[] not null default '{}',
  otras_redes_urls text[] not null default '{}',
  operadores_nombres text[] not null default '{}',
  operadores_tipos text[] not null default '{}',
  precio_mensual_uyu integer check (precio_mensual_uyu is null or precio_mensual_uyu between 10000 and 10000000),
  precio_fecha date,
  precio_incluye text[] not null default '{}',
  precio_fuente_url text,
  precio_es_demo boolean not null default false,
  msp_habilitado boolean not null default false,
  msp_fuente_url text,
  msp_fecha date,
  mides_certificado boolean not null default false,
  mides_fuente_url text,
  mides_fecha date,
  situacion text generated always as (
    case
      when msp_habilitado then 'habilitacion_msp'
      when mides_certificado then 'certificado_social_mides'
      else 'situacion_no_confirmada'
    end
  ) stored,
  descripcion text check (descripcion is null or char_length(btrim(descripcion)) between 1 and 2000),
  imagen_url text check (imagen_url is null or char_length(imagen_url) <= 1000),
  imagen_alt text check (imagen_alt is null or char_length(btrim(imagen_alt)) between 1 and 300),
  google_place_id text check (google_place_id is null or char_length(google_place_id) between 1 and 300),
  google_maps_url text check (
    google_maps_url is null
    or (
      char_length(google_maps_url) <= 1000
      and google_maps_url ~* '^https://((www\.)?google\.[a-z.]+/maps|maps\.google\.[a-z.]+/)'
    )
  ),
  google_verificado_at timestamptz,
  google_verificado_por text check (google_verificado_por is null or char_length(btrim(google_verificado_por)) between 1 and 200),
  osm_ids text[] not null default '{}',
  osm_urls text[] not null default '{}',
  otros_ids_proveedores text[] not null default '{}',
  otros_ids text[] not null default '{}',
  otros_ids_urls text[] not null default '{}',
  fuentes_referencias text[] not null,
  fuentes_urls text[] not null,
  fuentes_tipos text[] not null,
  fuentes_proveedores text[] not null,
  fuentes_fechas date[] not null,
  fuentes_consultadas_at timestamptz[] not null,
  fuentes_campos_respaldados text[] not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint elepem_unlocated_operator_arrays_aligned check (
    cardinality(operadores_nombres) = cardinality(operadores_tipos)
  ),
  constraint elepem_unlocated_osm_arrays_aligned check (
    cardinality(osm_ids) = cardinality(osm_urls)
  ),
  constraint elepem_unlocated_other_id_arrays_aligned check (
    cardinality(otros_ids_proveedores) = cardinality(otros_ids)
    and cardinality(otros_ids) = cardinality(otros_ids_urls)
  ),
  constraint elepem_unlocated_source_arrays_aligned check (
    cardinality(fuentes_referencias) >= 1
    and cardinality(fuentes_referencias) <= 200
    and cardinality(fuentes_referencias) = cardinality(fuentes_urls)
    and cardinality(fuentes_urls) = cardinality(fuentes_tipos)
    and cardinality(fuentes_tipos) = cardinality(fuentes_proveedores)
    and cardinality(fuentes_proveedores) = cardinality(fuentes_fechas)
    and cardinality(fuentes_fechas) = cardinality(fuentes_consultadas_at)
    and cardinality(fuentes_consultadas_at) = cardinality(fuentes_campos_respaldados)
  ),
  constraint elepem_unlocated_external_urls_check check (
    app_private.elepem_external_urls_valid(sitios_web)
    and app_private.elepem_external_urls_valid(instagram_urls)
    and app_private.elepem_external_urls_valid(facebook_urls)
    and app_private.elepem_external_urls_valid(otras_redes_urls)
    and app_private.elepem_external_urls_valid(osm_urls)
    and app_private.elepem_external_urls_valid(otros_ids_urls)
    and app_private.elepem_external_urls_valid(fuentes_urls)
  ),
  constraint elepem_unlocated_price_traceability_check check (
    (precio_mensual_uyu is null and precio_fecha is null and precio_fuente_url is null and not precio_es_demo)
    or (
      precio_mensual_uyu is not null
      and precio_fecha is not null
      and (precio_es_demo or precio_fuente_url ~* '^https?://')
    )
  ),
  constraint elepem_unlocated_msp_traceability_check check (
    (msp_habilitado and msp_fuente_url ~* '^https?://' and msp_fecha is not null)
    or (not msp_habilitado and msp_fuente_url is null and msp_fecha is null)
  ),
  constraint elepem_unlocated_mides_traceability_check check (
    (mides_certificado and mides_fuente_url ~* '^https?://' and mides_fecha is not null)
    or (not mides_certificado and mides_fuente_url is null and mides_fecha is null)
  ),
  constraint elepem_unlocated_google_manual_link_check check (
    (google_place_id is null and google_maps_url is null and google_verificado_at is null and google_verificado_por is null)
    or (
      google_place_id is not null
      and google_maps_url is not null
      and google_verificado_at is not null
      and google_verificado_por is not null
    )
  ),
  constraint elepem_unlocated_image_pair_check check (
    imagen_url is not null or imagen_alt is null
  )
);

create index elepem_departamento_idx on public.elepem (departamento);
create index elepem_localidad_idx on public.elepem (localidad);
create index elepem_situacion_idx on public.elepem (situacion);
create index elepem_msp_idx on public.elepem (msp_habilitado) where msp_habilitado;
create index elepem_mides_idx on public.elepem (mides_certificado) where mides_certificado;
create index elepem_coordinates_idx on public.elepem (lat, lng);
create index elepem_sin_ubicacion_departamento_idx on public.elepem_sin_ubicacion (departamento);

alter table public.elepem enable row level security;
alter table public.elepem force row level security;
alter table public.elepem_sin_ubicacion enable row level security;
alter table public.elepem_sin_ubicacion force row level security;

revoke all on table public.elepem from public, anon, authenticated, service_role;
revoke all on table public.elepem_sin_ubicacion from public, anon, authenticated, service_role;
revoke all on sequence public.elepem_id_seq from public, anon, authenticated, service_role;
revoke all on sequence public.elepem_sin_ubicacion_id_seq from public, anon, authenticated, service_role;
grant select on table public.elepem to service_role;

create trigger elepem_touch_updated_at
before update on public.elepem
for each row execute function app_private.touch_flat_elepem_updated_at();

create trigger elepem_sin_ubicacion_touch_updated_at
before update on public.elepem_sin_ubicacion
for each row execute function app_private.touch_flat_elepem_updated_at();

create temporary table arandu_elepem_flat_stage on commit drop as
select
  facility.id,
  facility.facility_key as codigo,
  legacy.legacy_residencial_id as legacy_id,
  preferred_name.name as nombre,
  coalesce(alternative_names.values, '{}')::text[] as nombres_alternativos,
  case lower(btrim(coalesce(current_address.department, origin_candidate.normalized_department)))
    when 'artigas' then 'Artigas'
    when 'canelones' then 'Canelones'
    when 'cerro largo' then 'Cerro Largo'
    when 'colonia' then 'Colonia'
    when 'durazno' then 'Durazno'
    when 'flores' then 'Flores'
    when 'florida' then 'Florida'
    when 'lavalleja' then 'Lavalleja'
    when 'maldonado' then 'Maldonado'
    when 'montevideo' then 'Montevideo'
    when 'paysandu' then 'Paysandú'
    when 'paysandú' then 'Paysandú'
    when 'rio negro' then 'Río Negro'
    when 'río negro' then 'Río Negro'
    when 'rivera' then 'Rivera'
    when 'rocha' then 'Rocha'
    when 'salto' then 'Salto'
    when 'san jose' then 'San José'
    when 'san josé' then 'San José'
    when 'soriano' then 'Soriano'
    when 'tacuarembo' then 'Tacuarembó'
    when 'tacuarembó' then 'Tacuarembó'
    when 'treinta y tres' then 'Treinta y Tres'
    else coalesce(current_address.department, origin_candidate.normalized_department)
  end as departamento,
  coalesce(current_address.locality, origin_candidate.normalized_locality) as localidad,
  coalesce(current_address.address_line, origin_candidate.normalized_address) as direccion,
  current_geocode.lat,
  current_geocode.lng,
  current_geocode.precision as precision_ubicacion,
  current_geocode.precision_label as precision_etiqueta,
  coalesce(contacts.phones, '{}')::text[] as telefonos,
  coalesce(contacts.emails, '{}')::text[] as emails,
  coalesce(websites.values, '{}')::text[] as sitios_web,
  coalesce(socials.instagram_urls, '{}')::text[] as instagram_urls,
  coalesce(socials.facebook_urls, '{}')::text[] as facebook_urls,
  coalesce(socials.other_urls, '{}')::text[] as otras_redes_urls,
  coalesce(operators.names, '{}')::text[] as operadores_nombres,
  coalesce(operators.types, '{}')::text[] as operadores_tipos,
  coalesce(profile.monthly_price_from_uyu, facility.demo_monthly_price_uyu) as precio_mensual_uyu,
  coalesce(profile.price_as_of, facility.demo_price_as_of) as precio_fecha,
  coalesce(profile.price_includes, facility.demo_price_includes, '{}')::text[] as precio_incluye,
  case when profile.monthly_price_from_uyu is not null then null::text else null::text end as precio_fuente_url,
  (profile.monthly_price_from_uyu is null and facility.demo_monthly_price_uyu is not null) as precio_es_demo,
  facility.registry_msp_final as msp_habilitado,
  case when facility.registry_msp_final then
    'https://www.gub.uy/ministerio-salud-publica/sites/ministerio-salud-publica/files/2026-06/ELEPEM%20HABILITADOS%20JUNIO%202026.pdf'
  end as msp_fuente_url,
  case when facility.registry_msp_final then coalesce(administrative.msp_date, date '2026-06-30') end as msp_fecha,
  facility.registry_mides_social as mides_certificado,
  case when facility.registry_mides_social then
    'https://www.gub.uy/ministerio-desarrollo-social/etiqueta/otros/establecimientos-larga-estadia-para-personas-mayores-certificado-social'
  end as mides_fuente_url,
  case when facility.registry_mides_social then coalesce(administrative.mides_date, date '2026-01-31') end as mides_fecha,
  profile.description as descripcion,
  profile.image_url as imagen_url,
  profile.image_alt as imagen_alt,
  google_id.external_id as google_place_id,
  google_id.external_url as google_maps_url,
  google_id.linked_at as google_verificado_at,
  google_id.linked_by as google_verificado_por,
  coalesce(osm_ids.ids, '{}')::text[] as osm_ids,
  coalesce(osm_ids.urls, '{}')::text[] as osm_urls,
  coalesce(other_ids.providers, '{}')::text[] as otros_ids_proveedores,
  coalesce(other_ids.ids, '{}')::text[] as otros_ids,
  coalesce(other_ids.urls, '{}')::text[] as otros_ids_urls,
  source_arrays.refs as fuentes_referencias,
  source_arrays.urls as fuentes_urls,
  source_arrays.types as fuentes_tipos,
  source_arrays.providers as fuentes_proveedores,
  source_arrays.source_dates as fuentes_fechas,
  source_arrays.retrieved_at as fuentes_consultadas_at,
  source_arrays.backed_fields as fuentes_campos_respaldados,
  facility.created_at,
  facility.updated_at,
  facility.registry_visibility,
  facility.location_status
from elepem_core.facilities as facility
join lateral (
  select name.name
  from elepem_core.facility_names as name
  where name.facility_id = facility.id and name.is_preferred
  order by name.id desc
  limit 1
) as preferred_name on true
left join lateral (
  select address.department, address.locality, address.address_line
  from elepem_core.facility_addresses as address
  where address.facility_id = facility.id
    and address.is_current
    and address.address_type = 'physical'
  order by address.id desc
  limit 1
) as current_address on true
left join discovery_private.facility_candidates as origin_candidate
  on origin_candidate.id = facility.origin_candidate_id
left join lateral (
  select geocode.lat, geocode.lng, geocode.precision, geocode.precision_label
  from elepem_core.facility_geocodes as geocode
  where geocode.facility_id = facility.id and geocode.is_current
  order by geocode.id desc
  limit 1
) as current_geocode on true
left join lateral (
  select mapping.legacy_residencial_id
  from elepem_core.legacy_facility_map as mapping
  where mapping.facility_id = facility.id and mapping.mapping_status = 'mapped'
  order by mapping.legacy_residencial_id
  limit 1
) as legacy on true
left join lateral (
  select array_agg(value order by value) as values
  from (
    select distinct name.name as value
    from elepem_core.facility_names as name
    where name.facility_id = facility.id and not name.is_preferred
  ) as distinct_names
) as alternative_names on true
left join lateral (
  select
    array_agg(contact.contact_value order by contact.id) filter (where contact.contact_type = 'phone') as phones,
    array_agg(contact.contact_value order by contact.id) filter (where contact.contact_type = 'email') as emails
  from elepem_core.facility_contacts as contact
  where contact.facility_id = facility.id and contact.is_current
) as contacts on true
left join lateral (
  select array_agg(value order by value) as values
  from (
    select contact.contact_value as value
    from elepem_core.facility_contacts as contact
    where contact.facility_id = facility.id and contact.is_current and contact.contact_type = 'website'
    union
    select observation.source_url
    from elepem_core.facility_observation_links as link
    join discovery_private.facility_source_observations as observation on observation.id = link.observation_id
    where link.facility_id = facility.id
      and observation.source_type = 'facility_website'
      and observation.source_url !~* '^https?://[^/]*supabase\.co(?:/|$)'
  ) as website_values
) as websites on true
left join lateral (
  select
    array_agg(value order by value) filter (where platform = 'instagram') as instagram_urls,
    array_agg(value order by value) filter (where platform = 'facebook') as facebook_urls,
    array_agg(value order by value) filter (where platform = 'other') as other_urls
  from (
    select distinct
      case
        when source_url ilike '%instagram.com/%' then 'instagram'
        when source_url ilike '%facebook.com/%' then 'facebook'
        else 'other'
      end as platform,
      source_url as value
    from (
      select account.public_url as source_url
      from elepem_core.facility_social_accounts as account
      where account.facility_id = facility.id and account.valid_to is null
      union
      select observation.source_url
      from elepem_core.facility_observation_links as link
      join discovery_private.facility_source_observations as observation on observation.id = link.observation_id
      where link.facility_id = facility.id
        and observation.source_type = 'social_public_url'
    ) as social_source
    where source_url !~* '^https?://[^/]*supabase\.co(?:/|$)'
  ) as social_values
) as socials on true
left join lateral (
  select
    array_agg(organization.legal_name order by relationship.id) as names,
    array_agg(relationship.relationship_type order by relationship.id) as types
  from elepem_core.facility_operators as relationship
  join elepem_core.organizations as organization on organization.id = relationship.organization_id
  where relationship.facility_id = facility.id and relationship.valid_to is null
) as operators on true
left join lateral (
  select
    max(event.effective_date) filter (where event.authority = 'MSP' and event.administrative_stage = 'authorization_final') as msp_date,
    max(event.effective_date) filter (where event.authority = 'MIDES' and event.administrative_stage = 'social_certificate') as mides_date
  from elepem_core.facility_administrative_events as event
  where event.facility_id = facility.id
) as administrative on true
left join elepem_core.facility_public_profiles as profile on profile.facility_id = facility.id
left join lateral (
  select external_id.external_id, external_id.external_url, external_id.linked_at, external_id.linked_by
  from discovery_private.facility_external_ids as external_id
  where external_id.facility_id = facility.id
    and external_id.provider = 'google_place'
    and external_id.link_method = 'manual'
  order by external_id.linked_at desc, external_id.id desc
  limit 1
) as google_id on true
left join lateral (
  select
    array_agg(external_id.external_id order by external_id.id) as ids,
    array_agg(coalesce(external_id.external_url, '') order by external_id.id) as urls
  from discovery_private.facility_external_ids as external_id
  where external_id.facility_id = facility.id and external_id.provider = 'openstreetmap'
) as osm_ids on true
left join lateral (
  select
    array_agg(external_id.provider order by external_id.id) as providers,
    array_agg(external_id.external_id order by external_id.id) as ids,
    array_agg(coalesce(external_id.external_url, '') order by external_id.id) as urls
  from discovery_private.facility_external_ids as external_id
  where external_id.facility_id = facility.id
    and external_id.provider not in ('google_place', 'openstreetmap')
) as other_ids on true
join lateral (
  select
    array_agg(source.reference order by source.sort_order, source.reference, source.url) as refs,
    array_agg(source.url order by source.sort_order, source.reference, source.url) as urls,
    array_agg(source.type order by source.sort_order, source.reference, source.url) as types,
    array_agg(source.provider order by source.sort_order, source.reference, source.url) as providers,
    array_agg(source.source_date order by source.sort_order, source.reference, source.url) as source_dates,
    array_agg(source.retrieved_at order by source.sort_order, source.reference, source.url) as retrieved_at,
    array_agg(source.backed_fields order by source.sort_order, source.reference, source.url) as backed_fields
  from (
    select
      1 as sort_order,
      'MSP:ELEPEM-HABILITADOS-JUNIO-2026'::text as reference,
      'https://www.gub.uy/ministerio-salud-publica/sites/ministerio-salud-publica/files/2026-06/ELEPEM%20HABILITADOS%20JUNIO%202026.pdf'::text as url,
      'official'::text as type,
      'MSP'::text as provider,
      coalesce(administrative.msp_date, date '2026-06-30') as source_date,
      facility.updated_at as retrieved_at,
      'msp_habilitado'::text as backed_fields,
      null::bigint as duplicate_rank
    where facility.registry_msp_final

    union all

    select
      2,
      'MIDES:CERTIFICADO-SOCIAL-ENERO-2026',
      'https://www.gub.uy/ministerio-desarrollo-social/etiqueta/otros/establecimientos-larga-estadia-para-personas-mayores-certificado-social',
      'official',
      'MIDES',
      coalesce(administrative.mides_date, date '2026-01-31'),
      facility.updated_at,
      'mides_certificado',
      null::bigint
    where facility.registry_mides_social

    union all

    select
      10,
      observation.source_record_key,
      case
        when observation.source_url ~* '^https?://[^/]*supabase\.co(?:/|$)' then ''
        else observation.source_url
      end,
      observation.source_type,
      coalesce(catalog.display_name, observation.source_type),
      observation.source_date,
      observation.retrieved_at,
      coalesce(nullif(concat_ws(',',
        case when observation.normalized_name is not null then 'nombre' end,
        case when observation.normalized_department is not null then 'departamento' end,
        case when observation.normalized_locality is not null then 'localidad' end,
        case when observation.normalized_address is not null then 'direccion' end,
        case when observation.lat is not null then 'ubicacion' end,
        case when observation.source_type = 'social_public_url' then 'red_social_publica' end
      ), ''), 'procedencia'),
      row_number() over (
        partition by observation.source_type, observation.source_record_key
        order by observation.retrieved_at desc, observation.id desc
      )
    from elepem_core.facility_observation_links as link
    join discovery_private.facility_source_observations as observation on observation.id = link.observation_id
    left join elepem_core.source_catalog as catalog on catalog.id = observation.source_catalog_id
    where link.facility_id = facility.id
      and observation.source_url !~* '^https?://(?:[^/]*\.)?google\.[^/]+/maps(?:/|$)'
      and observation.source_url !~* '^https?://maps\.app\.goo\.gl(?:/|$)'
  ) as raw_source(
    sort_order, reference, url, type, provider, source_date,
    retrieved_at, backed_fields, duplicate_rank
  )
  cross join lateral (
    select
      raw_source.sort_order,
      raw_source.reference,
      raw_source.url,
      raw_source.type,
      raw_source.provider,
      raw_source.source_date,
      raw_source.retrieved_at,
      raw_source.backed_fields
    where coalesce(raw_source.duplicate_rank, 1) = 1
  ) as source
) as source_arrays on true
where facility.lifecycle_status = 'current'
  and not facility.is_demo
  and (
    (facility.registry_visibility = 'public' and facility.location_status = 'mapped')
    or facility.location_status = 'location_pending'
  );

do $$
begin
  if (select count(*) from arandu_elepem_flat_stage
      where registry_visibility = 'public' and location_status = 'mapped') <> 1019 then
    raise exception 'Flat ELEPEM cutover expected 1019 mapped real rows';
  end if;
  if (select count(*) from arandu_elepem_flat_stage where location_status = 'location_pending') <> 83 then
    raise exception 'Flat ELEPEM cutover expected 83 current unlocated rows';
  end if;
  if exists (
    select 1
    from elepem_core.legacy_facility_map
    where mapping_status = 'mapped'
    group by facility_id
    having count(*) > 1
  ) then
    raise exception 'legacy_id cannot be flattened because a facility has multiple mapped legacy ids';
  end if;
  if exists (
    select 1 from arandu_elepem_flat_stage
    where cardinality(fuentes_referencias) = 0
  ) then
    raise exception 'Every flat ELEPEM row must preserve at least one source reference';
  end if;
  if exists (
    select 1 from arandu_elepem_flat_stage
    where departamento is null
      or localidad is null
      or (location_status = 'mapped' and direccion is null)
  ) then
    raise exception 'Flat ELEPEM cutover could not preserve the available location fields';
  end if;
  if exists (
    select report.facility_id
    from public.intake_reports as report
    join elepem_core.facilities as facility on facility.id = report.facility_id
    where not facility.is_demo
      and not exists (
        select 1 from arandu_elepem_flat_stage as target
        where target.id = report.facility_id
          and target.registry_visibility = 'public'
          and target.location_status = 'mapped'
      )
    union all
    select publication.facility_id
    from elepem_core.facility_experience_publications as publication
    join elepem_core.facilities as facility on facility.id = publication.facility_id
    where not facility.is_demo
      and not exists (
        select 1 from arandu_elepem_flat_stage as target
        where target.id = publication.facility_id
          and target.registry_visibility = 'public'
          and target.location_status = 'mapped'
      )
    union all
    select publication.facility_id
    from public.facility_change_publications as publication
    join elepem_core.facilities as facility on facility.id = publication.facility_id
    where not facility.is_demo
      and not exists (
        select 1 from arandu_elepem_flat_stage as target
        where target.id = publication.facility_id
          and target.registry_visibility = 'public'
          and target.location_status = 'mapped'
      )
    union all
    select review.facility_id
    from public.facility_document_status_reviews as review
    join elepem_core.facilities as facility on facility.id = review.facility_id
    where not facility.is_demo
      and not exists (
        select 1 from arandu_elepem_flat_stage as target
        where target.id = review.facility_id
          and target.registry_visibility = 'public'
          and target.location_status = 'mapped'
      )
  ) then
    raise exception 'A retained backend row references a real facility outside the 1019-row mapped target';
  end if;
  if exists (
    select 1 from public.intake_reports
    where demo_facility_id is not null
      and demo_facility_id <> 'DEMO-ELEPEM-001'
  ) then
    raise exception 'An intake report contains an unsupported pre-cutover demo facility key';
  end if;
  if exists (
    select 1
    from public.intake_reports as report
    where report.facility_id is not null
      and report.demo_facility_id is not null
      and not exists (
        select 1
        from elepem_core.facilities as facility
        where facility.id = report.facility_id
          and facility.is_demo
          and facility.facility_key = report.demo_facility_id
      )
  ) then
    raise exception 'An intake report contains inconsistent productive and demo facility references before cutover';
  end if;
end;
$$;

insert into public.elepem (
  id, codigo, legacy_id, nombre, nombres_alternativos,
  departamento, localidad, direccion, lat, lng, precision_ubicacion, precision_etiqueta,
  telefonos, emails, sitios_web, instagram_urls, facebook_urls, otras_redes_urls,
  operadores_nombres, operadores_tipos,
  precio_mensual_uyu, precio_fecha, precio_incluye, precio_fuente_url, precio_es_demo,
  msp_habilitado, msp_fuente_url, msp_fecha,
  mides_certificado, mides_fuente_url, mides_fecha,
  descripcion, imagen_url, imagen_alt,
  google_place_id, google_maps_url, google_verificado_at, google_verificado_por,
  osm_ids, osm_urls, otros_ids_proveedores, otros_ids, otros_ids_urls,
  fuentes_referencias, fuentes_urls, fuentes_tipos, fuentes_proveedores,
  fuentes_fechas, fuentes_consultadas_at, fuentes_campos_respaldados,
  created_at, updated_at
)
select
  id, codigo, legacy_id, nombre, nombres_alternativos,
  departamento, localidad, direccion, lat, lng, precision_ubicacion, precision_etiqueta,
  telefonos, emails, sitios_web, instagram_urls, facebook_urls, otras_redes_urls,
  operadores_nombres, operadores_tipos,
  precio_mensual_uyu, precio_fecha, precio_incluye, precio_fuente_url, precio_es_demo,
  msp_habilitado, msp_fuente_url, msp_fecha,
  mides_certificado, mides_fuente_url, mides_fecha,
  descripcion, imagen_url, imagen_alt,
  google_place_id, google_maps_url, google_verificado_at, google_verificado_por,
  osm_ids, osm_urls, otros_ids_proveedores, otros_ids, otros_ids_urls,
  fuentes_referencias, fuentes_urls, fuentes_tipos, fuentes_proveedores,
  fuentes_fechas, fuentes_consultadas_at, fuentes_campos_respaldados,
  created_at, updated_at
from arandu_elepem_flat_stage
where registry_visibility = 'public' and location_status = 'mapped';

insert into public.elepem_sin_ubicacion (
  id, codigo, legacy_id, nombre, nombres_alternativos,
  departamento, localidad, direccion,
  telefonos, emails, sitios_web, instagram_urls, facebook_urls, otras_redes_urls,
  operadores_nombres, operadores_tipos,
  precio_mensual_uyu, precio_fecha, precio_incluye, precio_fuente_url, precio_es_demo,
  msp_habilitado, msp_fuente_url, msp_fecha,
  mides_certificado, mides_fuente_url, mides_fecha,
  descripcion, imagen_url, imagen_alt,
  google_place_id, google_maps_url, google_verificado_at, google_verificado_por,
  osm_ids, osm_urls, otros_ids_proveedores, otros_ids, otros_ids_urls,
  fuentes_referencias, fuentes_urls, fuentes_tipos, fuentes_proveedores,
  fuentes_fechas, fuentes_consultadas_at, fuentes_campos_respaldados,
  created_at, updated_at
)
select
  id, codigo, legacy_id, nombre, nombres_alternativos,
  departamento, localidad, direccion,
  telefonos, emails, sitios_web, instagram_urls, facebook_urls, otras_redes_urls,
  operadores_nombres, operadores_tipos,
  precio_mensual_uyu, precio_fecha, precio_incluye, precio_fuente_url, precio_es_demo,
  msp_habilitado, msp_fuente_url, msp_fecha,
  mides_certificado, mides_fuente_url, mides_fecha,
  descripcion, imagen_url, imagen_alt,
  google_place_id, google_maps_url, google_verificado_at, google_verificado_por,
  osm_ids, osm_urls, otros_ids_proveedores, otros_ids, otros_ids_urls,
  fuentes_referencias, fuentes_urls, fuentes_tipos, fuentes_proveedores,
  fuentes_fechas, fuentes_consultadas_at, fuentes_campos_respaldados,
  created_at, updated_at
from arandu_elepem_flat_stage
where location_status = 'location_pending';

select setval('public.elepem_id_seq', (select max(id) from public.elepem), true);
select setval('public.elepem_sin_ubicacion_id_seq', (select max(id) from public.elepem_sin_ubicacion), true);

-- Move the single fictitious reference out of the productive registry.
-- The reserved demo row was removed by 20260810225000. Refuse to overwrite a
-- pre-existing row so the rollback can restore the exact pre-cutover state.
do $$
begin
  if exists (
    select 1 from arandu_demo.facilities where id = 'DEMO-ELEPEM-001'
  ) then
    raise exception 'DEMO-ELEPEM-001 already exists; refusing to overwrite pre-cutover demo state';
  end if;
  if has_schema_privilege('service_role', 'arandu_demo', 'usage')
    or has_column_privilege('service_role', 'arandu_demo.facilities', 'id', 'select') then
    raise exception 'Unexpected pre-cutover service_role grant on arandu_demo';
  end if;
end;
$$;

insert into arandu_demo.facilities (
  id, name, department, locality, address, description, phone, email,
  lat, lng, monthly_price_from_uyu, price_as_of, price_includes,
  image_url, image_alt, is_test, active
)
select
  facility.facility_key,
  preferred_name.name,
  current_address.department,
  current_address.locality,
  current_address.address_line,
  profile.description,
  coalesce(profile.contact_phone, '+598 000 001 001 (ficticio)'),
  coalesce(profile.contact_email, 'costa-serena@demo.invalid'),
  current_geocode.lat,
  current_geocode.lng,
  profile.monthly_price_from_uyu,
  profile.price_as_of,
  profile.price_includes,
  profile.image_url,
  profile.image_alt,
  true,
  true
from elepem_core.facilities as facility
join lateral (
  select name.name from elepem_core.facility_names as name
  where name.facility_id = facility.id and name.is_preferred
  order by name.id desc limit 1
) as preferred_name on true
join lateral (
  select address.department, address.locality, address.address_line
  from elepem_core.facility_addresses as address
  where address.facility_id = facility.id and address.is_current and address.address_type = 'physical'
  order by address.id desc limit 1
) as current_address on true
join lateral (
  select geocode.lat, geocode.lng
  from elepem_core.facility_geocodes as geocode
  where geocode.facility_id = facility.id and geocode.is_current
  order by geocode.id desc limit 1
) as current_geocode on true
join elepem_core.facility_public_profiles as profile on profile.facility_id = facility.id
where facility.is_demo and facility.facility_key = 'DEMO-ELEPEM-001'
on conflict (id) do update set
  name = excluded.name,
  department = excluded.department,
  locality = excluded.locality,
  address = excluded.address,
  description = excluded.description,
  phone = excluded.phone,
  email = excluded.email,
  lat = excluded.lat,
  lng = excluded.lng,
  monthly_price_from_uyu = excluded.monthly_price_from_uyu,
  price_as_of = excluded.price_as_of,
  price_includes = excluded.price_includes,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  is_test = true,
  active = true,
  updated_at = now();

-- Demo-linked reports use the isolated demo key. Production links preserve the
-- bigint id and are repointed to public.elepem below.
-- Drop the previous v3 ownership check before nulling facility_id: the old
-- check only knew about the normalized registry and would reject the demo key.
alter table public.intake_reports
  drop constraint if exists intake_reports_facility_id_fkey,
  drop constraint if exists intake_reports_experience_facility_v3_check,
  drop constraint if exists intake_reports_demo_facility_id_fkey;

update public.intake_reports as report
set
  demo_facility_id = facility.facility_key,
  facility_id = null,
  updated_at = now()
from elepem_core.facilities as facility
where report.facility_id = facility.id and facility.is_demo;

alter table public.intake_reports
  add constraint intake_reports_facility_id_fkey
    foreign key (facility_id) references public.elepem(id)
    on update cascade on delete restrict,
  add constraint intake_reports_demo_facility_id_fkey
    foreign key (demo_facility_id) references arandu_demo.facilities(id)
    on update cascade on delete restrict,
  add constraint intake_reports_experience_facility_v3_check check (
    entry_type <> 'experience'
    or payload_version < 3
    or num_nonnulls(facility_id, demo_facility_id) = 1
  );

drop trigger if exists facility_experience_publications_validate_report
  on elepem_core.facility_experience_publications;

alter table elepem_core.facility_experience_publications
  add column demo_facility_id text;

alter table elepem_core.facility_experience_publications
  drop constraint if exists facility_experience_publications_facility_id_fkey,
  drop constraint if exists facility_experience_publications_demo_facility_id_fkey,
  drop constraint if exists facility_experience_publications_owner_check,
  alter column facility_id drop not null;

update elepem_core.facility_experience_publications as publication
set demo_facility_id = facility.facility_key,
    facility_id = null
from elepem_core.facilities as facility
where publication.facility_id = facility.id and facility.is_demo;

alter table elepem_core.facility_experience_publications
  add constraint facility_experience_publications_facility_id_fkey
    foreign key (facility_id) references public.elepem(id)
    on update cascade on delete restrict,
  add constraint facility_experience_publications_demo_facility_id_fkey
    foreign key (demo_facility_id) references arandu_demo.facilities(id)
    on update cascade on delete restrict,
  add constraint facility_experience_publications_owner_check
    check (num_nonnulls(facility_id, demo_facility_id) = 1);

create or replace function elepem_core.validate_facility_experience_publication()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  linked_entry_type text;
  linked_facility_id bigint;
  linked_demo_facility_id text;
begin
  select report.entry_type, report.facility_id, report.demo_facility_id
  into linked_entry_type, linked_facility_id, linked_demo_facility_id
  from public.intake_reports as report
  where report.id = new.report_id;

  if not found then
    raise exception using errcode = '23503', message = 'publication requires an existing intake report';
  end if;
  if linked_entry_type <> 'experience' then
    raise exception using errcode = '23514', message = 'only experience intake reports can have public projections';
  end if;
  if linked_facility_id is distinct from new.facility_id
    or linked_demo_facility_id is distinct from new.demo_facility_id then
    raise exception using errcode = '23514', message = 'publication facility must match the intake report facility';
  end if;
  return new;
end;
$$;

revoke all on function elepem_core.validate_facility_experience_publication()
  from public, anon, authenticated, service_role;

create trigger facility_experience_publications_validate_report
before insert or update of report_id, facility_id, demo_facility_id, status
on elepem_core.facility_experience_publications
for each row execute function elepem_core.validate_facility_experience_publication();

alter table public.facility_change_publications
  add column demo_facility_id text;

alter table public.facility_change_publications
  drop constraint if exists facility_change_publications_facility_id_fkey,
  drop constraint if exists facility_change_publications_demo_facility_id_fkey,
  drop constraint if exists facility_change_publications_owner_check,
  alter column facility_id drop not null;

update public.facility_change_publications as publication
set demo_facility_id = facility.facility_key,
    facility_id = null
from elepem_core.facilities as facility
where publication.facility_id = facility.id and facility.is_demo;

alter table public.facility_change_publications
  add constraint facility_change_publications_facility_id_fkey
    foreign key (facility_id) references public.elepem(id) on delete restrict,
  add constraint facility_change_publications_demo_facility_id_fkey
    foreign key (demo_facility_id) references arandu_demo.facilities(id) on delete restrict,
  add constraint facility_change_publications_owner_check
    check (num_nonnulls(facility_id, demo_facility_id) = 1);

drop trigger if exists facility_document_status_reviews_append_only
  on public.facility_document_status_reviews;

alter table public.facility_document_status_reviews
  add column demo_facility_id text;

alter table public.facility_document_status_reviews
  drop constraint if exists facility_document_status_reviews_facility_id_fkey,
  drop constraint if exists facility_document_status_reviews_demo_facility_id_fkey,
  drop constraint if exists facility_document_status_reviews_owner_check,
  alter column facility_id drop not null;

update public.facility_document_status_reviews as review
set demo_facility_id = facility.facility_key,
    facility_id = null
from elepem_core.facilities as facility
where review.facility_id = facility.id and facility.is_demo;

alter table public.facility_document_status_reviews
  add constraint facility_document_status_reviews_facility_id_fkey
    foreign key (facility_id) references public.elepem(id) on delete restrict,
  add constraint facility_document_status_reviews_demo_facility_id_fkey
    foreign key (demo_facility_id) references arandu_demo.facilities(id) on delete restrict,
  add constraint facility_document_status_reviews_owner_check
    check (num_nonnulls(facility_id, demo_facility_id) = 1);

create trigger facility_document_status_reviews_append_only
before update or delete on public.facility_document_status_reviews
for each row execute function app_private.keep_facility_document_reviews_append_only();

drop view if exists public.facility_experiences_published;
create view public.facility_experiences_published
with (security_invoker = true, security_barrier = true)
as
select
  publication.id as publication_id,
  coalesce(facility.codigo, demo.id) as facility_key,
  publication.public_body,
  publication.public_relationship,
  publication.public_period,
  publication.published_at,
  report.is_demo
from elepem_core.facility_experience_publications as publication
left join public.elepem as facility on facility.id = publication.facility_id
left join arandu_demo.facilities as demo on demo.id = publication.demo_facility_id
join public.intake_reports as report on report.id = publication.report_id
where publication.status = 'published';

revoke all on table public.facility_experiences_published
  from public, anon, authenticated, service_role;
-- The security-invoker view needs only the fictitious identifier used by its
-- join. No other demo column becomes directly readable by service_role.
grant usage on schema arandu_demo to service_role;
grant select (id) on table arandu_demo.facilities to service_role;
grant select on table public.facility_experiences_published to service_role;

-- Permission probe: abort and roll back the whole cutover if the actual
-- runtime role cannot execute the public projection.
set local role service_role;
select count(*) as service_role_experience_view_probe
from public.facility_experiences_published;
reset role;

insert into elepem_core.audit_log (
  entity_type, entity_key, action, actor_identifier, after_state, request_id
)
select
  'registry_migration',
  'public.elepem:2026-08-13',
  'cutover_to_two_flat_tables',
  'operator-approved-flat-registry-plan',
  jsonb_build_object(
    'mapped_real', 1019,
    'unlocated_isolated', 83,
    'msp', 212,
    'mides', 275,
    'both', 170,
    'unconfirmed', 702,
    'synthetic_prices', 317,
    'automatic_publication', false,
    'legacy_tables_deleted', false
  ),
  '20260813120000'
where not exists (
  select 1 from elepem_core.audit_log
  where entity_type = 'registry_migration'
    and entity_key = 'public.elepem:2026-08-13'
    and request_id = '20260813120000'
);

do $$
begin
  if (select count(*) from public.elepem) <> 1019 then
    raise exception 'public.elepem must contain exactly 1019 rows after cutover';
  end if;
  if (select count(*) from public.elepem_sin_ubicacion) <> 83 then
    raise exception 'public.elepem_sin_ubicacion must contain exactly 83 rows after cutover';
  end if;
  if (select count(*) from public.elepem where msp_habilitado) <> 212
    or (select count(*) from public.elepem where mides_certificado) <> 275
    or (select count(*) from public.elepem where msp_habilitado and mides_certificado) <> 170
    or (select count(*) from public.elepem where not msp_habilitado and not mides_certificado) <> 702 then
    raise exception 'MSP/MIDES KPI reconciliation failed';
  end if;
  if (select count(*) from public.elepem where precio_es_demo) <> 317 then
    raise exception 'Expected 317 explicitly marked synthetic prices';
  end if;
  -- The live 2026-08-13 reconciliation yields 117 mapped rows and 39 of all
  -- 83 current unlocated rows. The older 33 figure counted only the 71-row
  -- pending-identity subset and omitted six verified rows from Canelones.
  if (select count(*) from public.elepem where departamento = 'Canelones') <> 117
    or (select count(*) from public.elepem_sin_ubicacion where departamento = 'Canelones') <> 39 then
    raise exception 'Canelones reconciliation failed';
  end if;
  if (select count(*) from public.elepem_sin_ubicacion where direccion is null) <> 26 then
    raise exception 'Expected 26 isolated rows whose source never supplied an address';
  end if;
  if exists (
    select 1 from public.elepem
    where cardinality(fuentes_referencias) <> cardinality(fuentes_urls)
       or cardinality(fuentes_urls) <> cardinality(fuentes_tipos)
       or cardinality(fuentes_tipos) <> cardinality(fuentes_proveedores)
       or cardinality(fuentes_proveedores) <> cardinality(fuentes_fechas)
       or cardinality(fuentes_fechas) <> cardinality(fuentes_consultadas_at)
       or cardinality(fuentes_consultadas_at) <> cardinality(fuentes_campos_respaldados)
  ) then
    raise exception 'At least one source array is misaligned';
  end if;
  if exists (
    select 1 from public.intake_reports
    where facility_id is not null
      and not exists (select 1 from public.elepem where id = intake_reports.facility_id)
  ) or exists (
    select 1 from elepem_core.facility_experience_publications
    where facility_id is not null
      and not exists (select 1 from public.elepem where id = facility_experience_publications.facility_id)
  ) or exists (
    select 1 from public.facility_change_publications
    where facility_id is not null
      and not exists (select 1 from public.elepem where id = facility_change_publications.facility_id)
  ) or exists (
    select 1 from public.facility_document_status_reviews
    where facility_id is not null
      and not exists (select 1 from public.elepem where id = facility_document_status_reviews.facility_id)
  ) then
    raise exception 'A retained backend table has an orphan productive facility reference';
  end if;
  if exists (
    select 1
    from elepem_core.facility_experience_publications as publication
    join public.intake_reports as report on report.id = publication.report_id
    where report.entry_type <> 'experience'
      and publication.status <> 'withdrawn'
  ) then
    raise exception 'A non-experience intake report has an active experience publication';
  end if;
end;
$$;

comment on table public.elepem is
  'Direct operational registry: one row per current, real and geolocated ELEPEM. No candidate or publication state.';
comment on table public.elepem_sin_ubicacion is
  'Exactly 83 current ELEPEM without usable coordinates. Isolated from APIs, map, search, KPI and foreign keys.';
comment on column public.elepem.precio_es_demo is
  'True only for synthetic demonstration prices. A real replacement requires amount, date and public source URL.';
comment on column public.elepem.situacion is
  'Display priority only: MSP, else MIDES, else situacion no confirmada. Filters use the two booleans independently.';

commit;
